spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
RESTTEMPLATE_URL: http://localhost:9001/orderdetails/get
FEIGN_CLIENT_URL: http://localhost:9001/orderdetails